openapi: 3.0.1
info:
  title: USPTO Trademark Checker
  version: "1.0"
paths:
  /check:
    post:
      summary: Check name availability
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                names:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Trademark check results
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        isAvailable:
                          type: boolean
